rootProject.name = "resourcemanagerhelper"
include("resourcemanagerhelper-api")
include("resourcemanagerhelper-v1_17_R1")
include("resourcemanagerhelper-v1_18_R1")
include("resourcemanagerhelper-v1_18_R2")
include("resourcemanagerhelper-v1_19_R1")
include("resourcemanagerhelper-v1_19_R2")
include("resourcemanagerhelper-v1_19_R3")
include("resourcemanagerhelper-v1_20_R1")
include("resourcemanagerhelper-v1_20_R2")
include("resourcemanagerhelper-v1_20_R3")
