name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual triggers

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-secret-keys

      - name: Set Snapshot or Release
        id: build-type
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "SNAPSHOT=true" >> $GITHUB_ENV
          else
            echo "SNAPSHOT=false" >> $GITHUB_ENV
          fi
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./gradlew clean publish